name: Terrapin Package Build

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@master
      name: Checkout source

    - name: Build package with Oryx
      run:  docker run --volume $(pwd):/repo --volume /home/runner/outputfolder:/output --env PRE_BUILD_COMMAND='chmod +x /repo/.github/workflows/terrapin-prebuild && /repo/.github/workflows/terrapin-prebuild && umask 0 && npm config set cache /tmp/.npm' mcr.microsoft.com/oryx/build:latest oryx build --package /repo/ --output /output -p registry=http://terrapin-dev-worker.azurewebsites.net/api/registry

    - uses: jikuma/githubaction@v0.3.3-alpha
      name: Create release
      with:
        operation: 'create a release'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release_title: 'Terrapin release'
        release_note: 'Job: 45582d0c-65f6-4024-a4c1-15fb22432b69 | Package: markdown-it-attrs@2.4.1 | Manager: Npm | Commit: ${{ github.sha }}'
        asset_filepath: '/home/runner/outputfolder/markdown-it-attrs-2.4.1.tgz'
        tag_name: v2.4.1+${{ github.sha }}
